export const addresses = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0x3eB708e689e1503569C136dED085e747f542d0EE",
    network: "bnb",
    img: "/bnb.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0x3eB708e689e1503569C136dED085e747f542d0EE",
    network: "ETH",
    img: "/sth-erc20.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TNbL6B2DadFpF5gtAur9LExrBM4YYxRPWd",
    network: "Tron TRC20",
    img: "/tron-bar.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TNbL6B2DadFpF5gtAur9LExrBM4YYxRPWd",
    network: "TRC20",
    img: "/usdt-trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qg42xrrd47sscp0p9pxdu7y7t6v469wplttzsjy",
    network: "Bitcoin",
    img: "/bitcoin-bar.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "8ttCpzhAUPFzuPiNFNFaqc3RUfcyxn3E7B7mRYqu8r7P",
    network: "Solana",
    img: "/sol.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQC7mPhvdMT-dYfAY0rAvNyeegWVkGg9-WGjhhiG8Zo6ZiQ2",
    network: "Ton",
    img: "/ton.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TNbL6B2DadFpF5gtAur9LExrBM4YYxRPWd",
    network: "Trc20",
    img: "/usdc.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0x3eB708e689e1503569C136dED085e747f542d0EE",
    network: "ERC20",
    img: "/busd.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rhhURprtsY4NB7SxT6hidvbVbjpk5JYDQn",
    network: "XRP",
    img: "/ripple.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0x3eB708e689e1503569C136dED085e747f542d0EE",
    network: "ERC20",
    img: "/usdt-erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0x3eB708e689e1503569C136dED085e747f542d0EE",
    network: "BEP20",
    img: "/usdt-bep20.png",
    logo: "./usdt.png",
  },
];

export const addressTwo = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0x9BaE3a95B9aBDf580Ca9c7D803e1C54747Fa0544",
    network: "bnb",
    img: "/bnb2.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0x9BaE3a95B9aBDf580Ca9c7D803e1C54747Fa0544",
    network: "ETH",
    img: "/eth2.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TBzJrLfn4LSwwEh2dw7ZWAYDGmhXcTdqKh",
    network: "Tron TRC20",
    img: "/trx2.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TBzJrLfn4LSwwEh2dw7ZWAYDGmhXcTdqKh",
    network: "TRC20",
    img: "/usdt2_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qwx0fywxt9479t40mkxk9lpu7fpkj078thvms3n",
    network: "Bitcoin",
    img: "/btc2.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "EQ1VwHriGTB4smxfbnzbaLj5PHZWpvEbJ3Cmk6jrJ335",
    network: "Solana",
    img: "/solana2.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: "EQCkhpM4vpL2VFcTdtjojVFkFlIv92leTdBzypfPRVlpNb3V",
    network: "Ton",
    img: "/ton2.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TBzJrLfn4LSwwEh2dw7ZWAYDGmhXcTdqKh",
    network: "Trc20",
    img: "/usdc2.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0x9BaE3a95B9aBDf580Ca9c7D803e1C54747Fa0544",
    network: "ERC20",
    img: "/busd2.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rpwKT2RJXgMeTs6kqwtwXzFoTfXMrdDwDq",
    network: "XRP",
    img: "/ripple2.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0x9BaE3a95B9aBDf580Ca9c7D803e1C54747Fa0544",
    network: "ERC20",
    img: "/usdt2_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0x9BaE3a95B9aBDf580Ca9c7D803e1C54747Fa0544",
    network: "BEP20",
    img: "/usdt2_bep20.png",
    logo: "./usdt.png",
  },
];

export const addressThree = [
  {
    id: 1,
    sym: "bnb",
    name: "BNB",
    address: "0xaF976dCCf75eac4474772aC5aA89b1052e799e75",
    network: "bnb",
    img: "/bnb3.png",
    logo: "https://w7.pngwing.com/pngs/1007/775/png-transparent-bnb-cryptocurrencies-icon.png",
  },

  {
    id: 2,
    sym: "ETH",
    name: "Ethereum",
    address: "0xaF976dCCf75eac4474772aC5aA89b1052e799e75",
    network: "ETH",
    img: "/eth3.png",
    logo: "/eth.png",
  },

  {
    id: 3,
    sym: "trx",
    name: "Tron",
    address: "TQZgv3FfsjkBUKueADRkQU9A5QkYAD2xMN",
    network: "Tron TRC20",
    img: "/trx3.png",
    logo: "/tron.png",
  },
  {
    id: 4,
    sym: "USDT",
    name: "USDT",
    address: "TQZgv3FfsjkBUKueADRkQU9A5QkYAD2xMN",
    network: "TRC20",
    img: "/usdt3_trc20.png",
    logo: "./usdt.png",
  },
  {
    id: 5,
    sym: "btc",
    name: "BTC",
    address: "bc1qg02p4gayf6kzpt6factgvq20mewcjaegs7pzkz",
    network: "Bitcoin",
    img: "/btc3.png",
    logo: "./btc.png",
  },
  {
    id: 6,
    sym: "sol",
    name: "Solana",
    address: "7VZDVK5y2GEf1yHZhekVrsmaEMNFEfGbjHNkntpVZs98",
    network: "Solana",
    img: "/solana3.png",
    logo: "https://w7.pngwing.com/pngs/248/72/png-transparent-sol-solana-coin-cryptocoin-exchange-coins-crypto-blockchain-cryptocurrency-logo-glyph-icon-thumbnail.png",
  },
  {
    id: 7,
    sym: "Ton",
    name: "TON",
    address: " EQDxaXfVktMLkbq6y3cQ-ovIsQWhFpIS3iJoQtIN_WAMXTDd",
    network: "Ton",
    img: "/ton3.png",
    logo: "https://ton.org/download/ton_symbol.png",
  },
  {
    id: 8,
    sym: "USDC",
    name: "USDC",
    address: "TQZgv3FfsjkBUKueADRkQU9A5QkYAD2xMN",
    network: "Trc20",
    img: "/usdc3_trc20.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Circle_USDC_Logo.svg/1024px-Circle_USDC_Logo.svg.png",
  },
  {
    id: 9,
    sym: "BUSD",
    name: "BUSD",
    address: "0xaF976dCCf75eac4474772aC5aA89b1052e799e75",
    network: "ERC20",
    img: "/busd3_trc20.png",
    logo: "https://altcoinsbox.com/wp-content/uploads/2023/01/binance-usd-busd-logo.webp",
  },
  {
    id: 10,
    sym: "XRP",
    name: "Ripple",
    address: "rw5DDAYvw1xhEr1W2yErwFxrTkA2QF2gax",
    network: "XRP",
    img: "/ripple3.png",
    logo: "https://w7.pngwing.com/pngs/35/349/png-transparent-xrp-cryptocurrency-logo-icon-thumbnail.png",
  },

  {
    id: 11,
    sym: "USDT",
    name: "USDT",
    address: "0xaF976dCCf75eac4474772aC5aA89b1052e799e75",
    network: "ERC20",
    img: "/usdt3_erc20.png",
    logo: "./usdt.png",
  },

  {
    id: 12,
    sym: "USDT",
    name: "USDT",
    address: "0xaF976dCCf75eac4474772aC5aA89b1052e799e75",
    network: "BEP20",
    img: "/usdt3_bep20.png",
    logo: "./usdt.png",
  },
];