export default [
  {
    id: 1,
    header: "1.1 Legal Notice",
    body: ` Before making use of our services, users should ensure that they are
    not a resident of a restricted area (Syria, Venezuela, and Zimbabwe)
          and that the country or region where they are located allows the use
          of our services. All legal risks and liabilities resulting from the
          illegal use of Volume Options services in the user’s country/region
          shall be solely borne by them.
          `,
  },
  {
    id: 2,
    header: "1.2 No Refunds",
    body: ` In accordance with the terms of this Agreement, replacements or refunds will not be issued once the user has made a successful purchase.
          `,
  },
  {
    id: 3,
    header: "1.3 Force Majeure Risk Statement",
    body: ` 1.3.1 If either party is unable to continue or must delay their performance of this Agreement in whole or in part due to force majeure, they shall notify the other party in writing or electronically within 20 days from the date of the occurrence of the force majeure event.
          `,
  },
  {
    id: 4,
    header: "",
    body: ` 1.3.2 The party suffering from force majeure shall take all necessary steps to reduce losses and resume their performance of this Agreement as soon as the event has passed, unless such performance is no longer possible or necessary.
          `,
  },
  {
    id: 5,
    header: "",
    body: ` 
1.3.3 The “force majeure” outlined in this Agreement refers to actual events that cannot be foreseen, avoided, or overcome, including but not limited to natural disasters (such as floods, fires, explosions, lightning strikes, earthquakes, and storms) and man-made events (such as wars, unrest, government regulation, national policies, sudden changes in laws, strikes, hacker or computer virus attacks, and technical adjustments in the telecommunications sector).
          `,
  },
  {
    id: 6,
    header: "1.4 Revisions to the Agreement",
    body: ` Taking into account the constantly shifting nature and content of Internet services, the user agrees that Volume Options has the right to modify the terms of this Agreement and notify the user of the revised Agreement through online or any other reasonable methods. The user agrees to visit the Volume Options website on a regular basis to review the latest Agreement. If the user does not agree with the terms of the revised Agreement, they should immediately cease using the services provided by Volume Options. The user’s continued use of the services provided by Volume Options will be deemed as an acceptance of the last revised Agreement.
          `,
  },
  {
    id: 7,
    header: "Definitions",
    body: `
          `,
  },
  {
    id: 8,
    header: "2.1 T-Day: A calendar day in Singapore time.",
    body: ``,
  },
  {
    id: 9,
    header:
      "2.2 Distributable Profit: Refers to beneficiary rights to the operating income based on Volume Options Earn holdings, including but not limited to the following after deduction of necessary expenses:",
    body: ``,
  },
  {
    id: 10,
    header: "",
    body: `2.2.1 Technical service fees generated by Volume Options Earn from the mining of blocks obtained through the DPOS mechanism.`,
  },
  {
    id: 11,
    header: "",
    body: `2.2.2 POS mining income generated by Volume Options Earn from holding POS mechanism tokens.`,
  },
  {
    id: 12,
    header: "",
    body: `2.2.3 Income generated by Volume Options Earn from providing related technical services to other DApp projects.`,
  },
  {
    id: 13,
    header:
      "2.3 Flexible Staking: Refers to POS staking products that can be redeemed at any time.",
    body: ``,
  },
  {
    id: 14,
    header:
      "2.4 Fixed Staking: Refers to staking products that can only be redeemed after a certain period.",
    body: ``,
  },
  {
    id: 15,
    header:
      "2.5 Total Assets Staked: Refers to the amount of tokens staked through Volume Options Earn events. This amount does not include products redeemed through the Earn platform.",
    body: ``,
  },
  {
    id: 16,
    header:
      "2.6 Staking: The act of locking up a certain amount of tokens onto the Volume Options Earn platform.",
    body: ``,
  },
  {
    id: 17,
    header:
      "2.7 Redemption: Staked tokens are unlocked and withdrawn to the Main Account on the date of redemption.",
    body: ``,
  },
  {
    id: 18,
    header: "",
    body: `2.7.1 Staked assets are usually redeemed (withdrawn) automatically to your Main Account on the date of redemption.

`,
  },
  {
    id: 19,
    header: "",
    body: `2.7.2 Users may choose to stake with flexible (can redeem at any time) or fixed products (can only redeem on the date of redemption).

`,
  },
  {
    id: 20,
    header: "",
    body: `2.7.3 Due to the restrictions of the on-chain rules of certain tokens, the redemption time must be configured in accordance with the requirements of the on-chain rules.
`,
  },
  {
    id: 21,
    header: "",
    body: `2.7.4 In most cases, redemption of flexible POL products is processed quickly, with an arrival time of no more than 2 hours. Fixed POL products generally have an arrival time of 1 day (24 hours). In the event of network delay or other incidents, contact customer service for assistance.
`,
  },
  {
    id: 22,
    header: "User Warrants and Representations",
    body: ``,
  },
  {
    id: 23,
    header:
      "3.1 The user hereby makes the following warrants and representations. Whenever the user makes use of our services, they are deemed to have repeated these warrants and representations.",
    body: ``,
  },
  {
    id: 24,
    header: "",
    body: `3.1.2 As a legal person or organization, the user has the full legal capacity and authorization required to enter into and be bound by this Agreement.`,
  },
  {
    id: 25,
    header: "",
    body: `3.1.3 In using the services provided by us, the user does not violate nor contravene any laws that are applicable to them, and/or any contractual restrictions that bind or otherwise affect them or any of their assets related to the use of our services. The user has not been subject to any economic sanctions administered or enforced by any relevant country, government, or international agency (including but not limited to the Office of Foreign Assets Control of the US Department of the Treasury, the U.S. Department of State, the United Nations Security Council, the European Union, the HM Treasury, the Hong Kong Monetary Authority, or the Monetary Authority of Singapore).`,
  },
  {
    id: 26,
    header: "",
    body: `3.1.4 The user is only using our services for their own purposes, meaning that they are not using our services on the behalf of anyone else and there are no third-party beneficiaries without our prior approval.`,
  },
  {
    id: 27,
    header:
      "3.2 With regard to registration data and information provided by the user (“Registration Information”), the user warrants the following.",
    body: ``,
  },
  {
    id: 28,
    header: "",
    body: `3.2.1 That all registration information provided is legal, true, accurate, and complete.`,
  },
  {
    id: 29,
    header: "",
    body: `3.2.2 If there are any changes to the provided registration information, the user will notify Volume Options in a prompt manner. If the registration information provided by the user is illegal, untrue, inaccurate, or incomplete, they shall bear all corresponding liabilities and consequences.`,
  },
  {
    id: 30,
    header: "",
    body: `3.2.3 Volume Options reserves the right to impose certain restrictions on accounts and/or suspend or terminate the provision of Volume Options services in accordance with the provided registration information and its compliance obligations and internal risk control policies.`,
  },
  {
    id: 30,
    header: "",
    body: `3.2.4 Each user may only register one account on Volume Options unless they have prior written consent.`,
  },
  {
    id: 31,
    header: "",
    body: `3.2.5 Volume Options reserves the right to request that the user provide identifying information on the account owner and/or financial information for compliance purposes such as Know Your Customer (KYC) and/or anti-money laundering (AML).`,
  },
  {
    id: 32,
    header: "",
    body: `3.2.6 The user may need to enter their username and password to access certain functions provided by Volume Options. If the user loses access to their account due to reasons such as forgetting their password, Volume Options has the right to request that they provide specific information such as identification information to verify their ownership of the account. This includes but is not limited to proof of identity, proof of residency, proof of phone number/email, and any identifiable website activity such as transaction IDs, order numbers, and withdrawal amounts. The user warrants that they will not share their username and/or password with anyone or allow any third-party access to their account. Volume Options does not assume any responsibility for the improper use of the user’s username and password, any third-party access, or the resulting consequences therefrom. If the user believes their username/password has been compromised or their account has been used by someone else without their authorization, they should notify Volume Options immediately.`,
  },
  {
    id: 32,
    header: "Risk Disclosure",
    body: ``,
  },
  {
    id: 33,
    header:
      "4.1 The user understands and recognizes that the purchase of financial products and related services during operation involves certain risks, and that the risks outlined in Article 4.1 of this Agreement are not an exhaustive list. These risks and any other risks that arise now or in the future may cause the user to be unable to obtain any benefits, suffer financial losses, or even the termination of our services.",
    body: ``,
  },
  {
    id: 34,
    header: "",
    body: `4.1.1 The purchase of financial products and the services associated with its operation all entail potential financial, regulatory, and other risks. Before purchasing financial products and making use of the related services, the user should ensure that they have sufficient experience and knowledge in blockchain technology, product functionality, and the associated risks. Any decision by the user to participate in any purchase of financial products and related services associated with its operation should be based on due diligence and/or professional consultation as deemed necessary by the user. Volume Options assumes that the user is a professional who understands the industry and the risks of services related to the purchase. This Agreement and any services provided by Volume Options shall not be regarded as financial advice.`,
  },
  {
    id: 35,
    header: "",
    body: `4.1.2 The value of any financial product offered by Volume Options may be affected by factors not under the control of Volume Options, including but not limited to changes in product parameters/attributes, market volatility, hardware obsolescence, and hardware amortization.`,
  },
  {
    id: 36,
    header: "",
    body: `4.1.3 Volume Options may upgrade or carry out maintenance on its systems from time to time. The user hereby confirms that they do not expect the services provided by Volume Options to be continuous or uninterrupted. Unless otherwise expressly agreed upon by both parties, Volume Options shall not be liable for any and all losses resulting from the suspension or interruption of its services for maintenance or upgrade.`,
  },
  {
    id: 37,
    header: "",
    body: `4.1.4 No authentication method or security technology is 100% secure. The user agrees to assume all the risks associated with hacking or identity theft.`,
  },
  {
    id: 38,
    header: "",
    body: `4.1.5 The user understands and agrees that Volume Options has the right to publish, modify, and/or provide information related to its services through website, email, customer service call, mobile text message, and other official channels. Volume Options is not responsible for any information obtained through non-official channels. If users have any doubts about the authenticity of information sent from a source claiming to be Volume Options, they should contact us immediately.`,
  },
  {
    id: 39,
    header:
      "4.2 Before purchasing any financial product provided by Volume Options, users should evaluate whether the financial product is suited for their financial resources and risk appetite. When a user purchases any financial product provided by Volume Options, they are deemed to have recognized, understood, and accepted all risks related to mining, buying, selling, exchanging, and holding the financial product. This includes but is not limited to:",
    body: ``,
  },
  {
    id: 40,
    body: "4.2.1 Market fluctuations, with the possibility of prices experiencing sharp declines or even dropping to zero.",
    header: ``,
  },
  {
    id: 41,
    body: "4.2.2 Waiting periods before transactions can be confirmed. There is a possibility that certain transactions may never be confirmed, though this is unlikely. When a transaction is unconfirmed, this means that it has not been completed.",
    header: ``,
  },
  {
    id: 42,
    body: "4.2.3 Transactions are irreversible. The user will not be able to reverse transactions of any amount of funds to an incorrect person or address, nor will they be able to recover the funds.",
    header: ``,
  },
  {
    id: 43,
    header: "",
    body: `4.2.4 If the user forgets any PIN or password required for the access or operation of their funds, those funds may be lost or otherwise rendered unavailable.`,
  },
  {
    id: 44,
    header: "",
    body: `4.2.5 Blockchain technology may possess inherent unknown technical defects.`,
  },
  {
    id: 45,
    header: "",
    body: `4.2.6 Certain countries or regions may introduce new laws, regulations, or policies that affect the performance of this Agreement.`,
  },
  {
    id: 46,
    header: "Order Payment, Cancelation, Modification, and Refund",
    body: ``,
  },
  {
    id: 47,
    header:
      "5.1 The user may purchase financial products with the payment methods supported by Volume Options.",
    body: ``,
  },
  {
    id: 48,
    header:
      "5.2 The user is solely responsible for the accuracy of the payment, including but not limited to the destination account address (wallet address), transfer amount, and other payment details. Any losses resulting from wrong payment due to user error (such as transferring funds to the wrong address) shall be borne entirely by the user. Volume Options reserves the right to require that the user make an accurate payment before activating any financial products.",
    body: ``,
  },
  {
    id: 49,
    header:
      "5.3 If the amount actually received is lower than the fees required, Volume Options reserves the right to engage in the following actions at its own discretion before activating the corresponding financial products:",
    body: ``,
  },
  {
    id: 50,
    header: "",
    body: `5.3.1 Adjust the financial product so that the funds actually received by Volume Options match the content of the provided financial product.`,
  },
  {
    id: 51,
    header: "",
    body: `
5.3.2 Refuse to activate the financial product ordered by the user until the amount owed has been paid.
`,
  },
  {
    id: 52,
    header:
      "5.4 Due to the time required to confirm transactions and other third-party delays, there is a risk that the amount transferred by the user to Volume Options may be delayed. The user agrees that Volume Options has the right to confirm the arrival of the full amount before activating the corresponding financial products.",
    body: ``,
  },
  {
    id: 53,
    header:
      "5.5 To the fullest extent permitted by laws and regulations, the user acknowledges that unless they otherwise receive express agreement in writing, all purchased financial products are final, non-replaceable, and non-refundable. Volume Options reserves the right to issue refunds at its sole discretion. The provision of a refund for a specific user or financial product does not obligate Volume Options to agree to issue the same or similar refund in the future. This refund policy does not affect any applicable statutory rights.",
    body: ``,
  },
  {
    id: 53,
    header:
      "5.6 Subject to the other terms of this Agreement, any additional fees (such as third-party fees) arising from the provision of refunds by Volume Options in accordance with this agreement or applicable laws and regulations shall be borne entirely by the user.",
    body: ``,
  },
  {
    id: 54,
    header: "Mining Pool Rules",
    body: ``,
  },
  {
    id: 55,
    header: "6.1 Staking Income and POL Distribution Rules:",
    body: ``,
  },
  {
    id: 56,
    header: "",
    body: `6.1.1 Digital assets deposited by users on the platform can be used to subscribe to financial products to obtain POL and POS staking income.`,
  },
  {
    id: 57,
    header: "",
    body: `6.1.2 Users can subscribe to basic financial products (the adjusted market value of digital assets deposited by users on the Earn platform) by staking tokens.`,
  },
  {
    id: 58,
    header: "",
    body: `6.1.3 Deposit Market Value Formula: market value of deposit = deposit amount market index price variety adjustment ratio.`,
  },
  {
    id: 59,
    header: "",
    body: `6.1.4 Deposit Amount: Volume Options Earn converts tokens deposited by customers into BTC in accordance with the market index based on the daily liquidity evaluation index. The converted BTC serves as the basic financial product of users on Volume Options Earn.`,
  },
  {
    id: 60,
    header: "",
    body: `6.1.5 Settlement Rules: If a user transfers in assets before 22:00 on T day, the income will be calculated on T+1 day and available for withdraw on T+2 day.`,
  },
  {
    id: 61,
    header:
      "6.2 Redemption Rules: After the locking period of staked assets ends, Volume Options will automatically release the assets to user’s Main Account opened in the platform.",
    body: ``,
  },
  {
    id: 62,
    header: "6.3 POL Income:",
    body: ``,
  },
  {
    id: 63,
    header: "",
    body: `6.3.1 The platform will transfer POS/DPOS node income generated on T day into the airdrop pool on a daily basis. Profits in the airdrop pool are included in the reward pool, while other revenue from the mining pool is distributed to the airdrop pool each day.`,
  },
  {
    id: 64,
    header: "",
    body: `6.3.2 The platform takes a snapshot of the staked balance in the Volume Options Earn system at 22:00 on T day. On T+1 day, funds will be automatically distributed to all holders in accordance with the positions on the Earn platform.`,
  },
  {
    id: 65,
    header: "User Restrictions and Obligations",
    body: ``,
  },
];
